name: Terraform GCP GCE Provision

on:
  push:
    branches:
      - main

env:
  TF_VAR_project_id: arboreal-cosmos-440011-r8
  TF_VAR_service_account_email: "akm99-119@arboreal-cosmos-440011-r8.iam.gserviceaccount.com"

jobs:
  terraform:
    name: Terraform Provisioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_AKM }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
